
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/container";
import { getServerSession } from "next-auth";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import  SessionProvider  from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={`${inter.className} text-white dark`}>
        <SessionProvider session={session}>
        <Container>
          <Navbar/>

        {children}

        <Footer/>
        </Container>
        </SessionProvider>

      </body>
    </html>
  );
}
